/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sajal;

//import com.sajal.A;
import com.sajal.Task1.Plane;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ApplicationContext context = SpringApplication.run(App.class,args);

        Plane plane = context.getBean(Plane.class);
        plane.moveUp();
        plane.moveFront();
        plane.moveDown();
        plane.getPosition();

        A a = context.getBean(A.class);
        System.out.println(a.getSum(1,2));
        a.printHello();
        a.getNum();

    }
}
